### ISSUE TITLE
`conda` / `micromamba` environments

### ISSUE THREAD

**Issue by kwolz** [simonsobs/SOOPERCOOL#27]
(This might be a [`NaMaster`](https://github.com/LSSTDESC/NaMaster/tree/master/pymaster) issue, happy to post it there if needed.)
For cleanliness and a robust python environment at clusters like NERSC or Blackett it is desirable to run the pipeline in a single `conda` or `micromamba` environment. 

I tested this and found it is currently impossible: the conda-forge version of `NaMaster` needs `python <= 3.6`, while `TOAST` needs the newest python version. As a workaround, I set up two `micromamba` environments at NERSC (see [INSTALL.md](https://github.com/simonsobs/SOOPERCOOL/blob/validation/INSTALL.md)) and load `TOAST` only for the filtering stages (see commented lines in [pipeline/run_all.sh](https://github.com/simonsobs/SOOPERCOOL/blob/validation/pipeline/run_all.sh)). 

Has anyone else encountered this issue?

**Comment by susannaaz** [comment]
Hey Kevin, I did and managed to create a conda environment using python 3.9 where I can use both `TOAST` and `NaMaster`. The environment can be found in my `$PSCRATCH` on NERSC and is open to everyone: `/pscratch/sd/s/susannaz/conda_envs/`. I never used micromamba but this has been working fine for me so far!

**Comment by kwolz** [comment]
Cool! Will try this right away. Is it called `master_env`?

**Comment by kwolz** [comment]
I'm getting the following error (which is the same I got before with my own environment):
```
(/pscratch/sd/s/susannaz/conda_envs/master_env) kwolz@login32:~/bbdev/SOOPERCOOL> python -c 'import pymaster; import toast'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pymaster/__init__.py", line 50, in <module>
    from pymaster import nmtlib as lib  # noqa
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pymaster/nmtlib.py", line 13, in <module>
    import _nmtlib
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```
Maybe it is related to my local environment (PATH, LD_LIBRARY_PATH, etc.), but the only way I could avoid this way by using `python=3.6` as environment.
Does this test pass for you?

**Comment by susannaaz** [comment]
It does pass for me (see picture) - maybe try commenting out all the local environment variables in your `.bashrc`, then do `module load python/3.9-anaconda-2021.11` before you activate the environment? Let me know if that doesn't work

![condamaster](https://github.com/simonsobs/SOOPERCOOL/assets/47179252/d8340680-a208-4c2b-9505-37cb7d36198d)

**Comment by kwolz** [comment]
I'm still getting the same error. Can you print the output of `module list` to check?

**Comment by susannaaz** [comment]
```
Currently Loaded Modules:
  1) craype-x86-milan                        6) cray-dsmml/0.2.2       11) perftools-base/23.03.0   16) craype-accel-nvidia80
  2) libfabric/1.15.2.0                      7) cray-libsci/23.02.1.1  12) cpe/23.03                17) gpu/1.0
  3) craype-network-ofi                      8) cray-mpich/8.1.25      13) Nsight-Compute/2022.1.1  18) evp-patch
  4) xpmem/2.6.2-2.5_2.33__gd067c3f.shasta   9) craype/2.7.20          14) Nsight-Systems/2022.2.1  19) python/3.9-anaconda-2021.11 (dev)
  5) PrgEnv-gnu/8.3.3                       10) gcc/11.2.0             15) cudatoolkit/11.7
```

**Comment by susannaaz** [comment]
I can include some general instructions to set up the same working environment I have if that helps!

**Comment by kwolz** [comment]
That would be awesome! Feel free to overwrite the above [INSTALL.md](https://github.com/simonsobs/SOOPERCOOL/blob/validation/INSTALL.md), I have a local copy of what I did.

**Comment by kwolz** [comment]
BTW, `python -c 'import pymaster'` works now :) 
I didn't have the same module environment loaded and loading some of them (`Nsight-Compute/2022.1.1`, `Nsight-Systems/2022.2.1`, `cudatoolkit/11.7`, `craype-accel-nvidia80`, `gpu/1.0`) resolved the issue. 
It will in any case be super helpful to have the detailed instructions!
The other, minor, thing is that if I try to load `toast` using your environment, then I get the following permission error. It might be helpful to store the environment under `/global/common/software` so this is automatically accessible for `mp107` users.

```
(/pscratch/sd/s/susannaz/conda_envs/master_env) kwolz@nid200041:/global/u2/k/kwolz/bbdev/SOOPERCOOL/pipeline> python -c 'import toast'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/toast/__init__.py", line 98, in <module>
    from .weather import Weather
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/toast/weather.py", line 12, in <module>
    from pkg_resources import resource_filename
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2134, in find_on_path
    for dist in factory(fullpath):
  File "/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2192, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
PermissionError: [Errno 13] Permission denied: '/pscratch/sd/s/susannaz/conda_envs/master_env/lib/python3.9/site-packages/astroid-3.0.1.dist-info'
```
